name: Game Monitor

on:
  schedule:
    - cron: "*/5 * * * *"   # every 5 minutes
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install jq -y

      - name: Run script
        run: bash monitor.sh
        env:
          COOKIE_KEY: ${{ secrets.COOKIE_KEY }}
          DISCORD_WEBHOOK200: ${{ secrets.DISCORD_WEBHOOK200 }}
          DISCORD_WEBHOOK500: ${{ secrets.DISCORD_WEBHOOK500 }}
          DISCORD_WEBHOOK300: ${{ secrets.DISCORD_WEBHOOK200 }}
          DISCORD_WEBHOOK400: ${{ secrets.DISCORD_WEBHOOK200 }}
          DISCORD_WEBHOOK1000: ${{ secrets.DISCORD_WEBHOOK1000 }}
          LINK: ${{ secrets.LINK }}
